server:
  port: 8201
  
spring:
  profile: dev
  application:
    name: microservicecloud-config-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/    
---

server:
  port: 8202
  
spring:
  profile: test
  application:
    name: microservicecloud-config-client-test

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/    
  
